#!/bin/bash
# postinst script for bluetooth-sensor-scanner

set -e

case "$1" in
    configure)
        # Make the script executable
        chmod +x /usr/bin/ws-bluetooth-devices
        
        # Enable the timer using deb-systemd-helper
        deb-systemd-helper unmask ws-bluetooth-scanner.timer >/dev/null || true
        deb-systemd-helper enable ws-bluetooth-scanner.timer >/dev/null || true
        deb-systemd-invoke start ws-bluetooth-scanner.timer >/dev/null || true
        ;;
    
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
