#!/bin/bash
# postrm script for bluetooth-sensor-scanner

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        # Reload systemd configuration to clean up
        systemctl daemon-reload || true
        ;;
    
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
